backend/atm_system/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('',include('core.urls')),
    path('admin/', admin.site.urls)
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

backend/core/urls.py
from django.urls import path

from .views import * 

app_name = 'core'

urlpatterns = [

    path('login/',Login,name='login'),
    path('FaceRegognation/',FaceAuthentication,name='FaceRegognation'),
    path('submitFace/',submitFace,name='submitFace'),
    path('submit_otp/',submit_otp,name='submit_otp'),
    path('api_send_otp/',api_send_otp,name='api_send_otp'),
    path('api_check_balance/',api_check_balance,name='api_check_balance'),
    path('getFingerprint/',getFingerprint,name='getfingerprint'),
    path('deductbalance/',deductBalance,name='deductbalance'),


    path('FingerPrintAuth/',FingerPrintAuth,name='FingerPrintAuth'),
]

backend/templates/account_selection.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container-fluid">
    <div class="account_type">
    <a href="{% url 'core:balance' %}"><button class="btn account_type_btn">Current</button></a>
    <a href="{% url 'core:balance' %}"><button class="btn account_type_btn">Saving</button></a>
    <a href="{% url 'core:balance' %}"><button class="btn account_type_btn">Default</button></a>
    </div>
</div>
{% endblock %}

backend/templates/balance.html
{% extends 'base.html' %}

{% block content %}
<div class="container-fluid">
    <div class="form-div">
        {% if message %}
        <div class="alert alert-danger">
            {{message}}
        </div>
        {% endif %}
        <form action="{% url 'core:balance' %}" method="POST"
            class="d-flex flex-row flex-wrap justify-content-center mt-3 balance_form">
            <div class="alert alert-danger w-100" style="display: none;">
                Invalid Ammount
            </div>
            {% csrf_token %}
            <input type="number" class="form-control amount_input" placeholder="Enter Ammount" name="ammount" value=""
                required>
            <Button class="btn btn-primary w-25 mt-4 balance_submit_btn" type="submit">Submit</Button>
        </form>


        <form class="face-recognation-submit" enctype="multipart/form-data" method="POST"
            action="{% url 'core:balance' %}" hidden>
            {% csrf_token %}
            <video id="video" width="320" height="240" autoplay hidden></video>
            <canvas id="canvas" width="320" height="240" hidden name="image"></canvas>
            <input type="text" id="canvasData" name="canvasData" hidden />
            <input type="text" value="{{last_verified}}" name="last_authentication" class="last_authentication_input"
                hidden>
            <input type="text" value="" name="amount" class="amount_input_submit" hidden value="0.00">
        </form>


        <form action="{% url 'core:submit_otp' %}" method="post" class="phone_submit" id="phone_submit" hidden>
            {% csrf_token %}
            <div class="card py-5 px-3">
                <h5 class="m-0">Mobile phone verification</h5><span class="mobile-text">Enter the code we just send on
                    your mobile phone <b class="text-danger">{{phone_num}}</b></span>
                <div class="d-flex flex-row mt-5"><input type="text" class="form-control" autofocus="" name="otp"></div>
                <input type="text" class="form-control" autofocus="" name="resubmit" value="true" hidden>
                <input type="text" class="account_id" value="{{account_id}}" hidden>
                <input type="text" name="amount" id="phone_amount" value="0.00" hidden>
                <button class="btn btn-primary mt-3" type="submit">Submit</button>
            </div>
        </form>

    </div>
</div>
{% endblock %}

{% block script %}
<script>
    $(document).ready(function () {
        $('.balance_form').submit(() => {
            event.preventDefault();
            var last_auth = document.querySelector('.last_authentication_input').value;
            if (last_auth === '1') {
                let camera_button = document.querySelector(".balance_submit_btn");
                let video = document.querySelector("#video");
                let canvas = document.querySelector("#canvas");

                camera_button.addEventListener('click', async function () {
                    let stream = await navigator.mediaDevices.getUserMedia({
                        video: true,
                        audio: false
                    });
                    video.srcObject = stream;


                    setTimeout(() => {
                        canvas.getContext('2d').drawImage(video, 0, 0, canvas.width,
                            canvas
                            .height);
                        let image_data_url = canvas.toDataURL('image/jpeg', 1.0);


                        stream.getTracks().forEach(function (track) {
                            track.stop();
                        });
                        $('#canvasData')[0].value = image_data_url;
                        $('.amount_input_submit').val($('.amount_input').val());

                        var formdata = document.querySelector(
                            '.face-recognation-submit').submit();
                    }, 3000);

                });
            } else if (last_auth === '3') {
                $('#phone_amount').val($('.amount_input').val());
                fetch('/api_check_balance/', {
                        method: "POST",
                        headers: {
                            'Content-Type': "Application/json",
                            "X-CSRFToken": getCsrfToken("csrftoken")
                        },
                        body: JSON.stringify({
                            "account_id": $('.account_id').val(),
                            "amount": $('#phone_amount').val()
                        })
                    })
                    .then(response => response.json())
                    .then(result => {
                        if (result.status === 'ok') {
                            fetch('/api_send_otp/', {
                                    method: "POST",
                                    headers: {
                                        'Content-Type': "Application/json",
                                        "X-CSRFToken": getCsrfToken("csrftoken")
                                    },
                                    body: JSON.stringify({
                                        "account_id": $('.account_id').val(),
                                    })
                                })
                                .then(response => response.json())
                                .then(result => {
                                    if (result.status == 'ok') {
                                        document.querySelector('.phone_submit').removeAttribute(
                                            'hidden');
                                    }
                                })
                        } else {
                            document.querySelector('.alert-danger').innerText = result.message;
                            document.querySelector('.alert-danger').style.display = 'block';
                        }
                    })
            }
        });
    });

    function getCsrfToken(name) {
        // Split cookie string and get all individual name=value pairs in an array
        var cookieArr = document.cookie.split(";");

        // Loop through the array elements
        for (var i = 0; i < cookieArr.length; i++) {
            var cookiePair = cookieArr[i].split("=");

            /* Removing whitespace at the beginning of the cookie name
            and compare it with the given string */
            if (name == cookiePair[0].trim()) {
                // Decode the cookie value and return
                return decodeURIComponent(cookiePair[1]);
            }
        }

        // Return null if not found
        return null;
    }

</script>
{% endblock %}

backend/templates/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>ATM SYSTEM</title>
    <link rel="stylesheet" href="{% static 'css/main.css'%}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>

<body>
    <div class="bg-image"></div>
    {% block content  %}
    {% endblock content %}

    {% block script %}
    {% endblock %}
</body>

</html>

backend/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="form-div">
    <form class="face-recognation-form" enctype="multipart/form-data" method="POST" action="{% url 'core:FaceRegognation' %}">
        {% csrf_token %}
        <video id="video" width="320" height="240" autoplay hidden></video>
        <canvas id="canvas" width="320" height="240" hidden name="image"></canvas>
        <input type="text" id="canvasData" name="canvasData" hidden/>
    </form>

    <h1>Select The Authentication Type</h1>
    {% if message %}
    <div class="alert alert-warning">
        {{message}}
    </div>
    {% endif %}
    <div class="d-flex flex-wrap">
        <button class="btn btn-light mt-3 p-2 w-100" id="face_authentication-btn">Face Authentication</button>
        <button class="btn btn-light mt-3 p-2 w-100" id="finger_print-btn">Finger Print Authentication</button>
        <a href="{% url 'core:phone_authentication'%}" class="w-100"><button class="btn btn-light mt-3 p-2 w-100">Phone Authentication</button></a>
    </div>
</div>
{% if message == 'otp is send to the registered mobile number' %}
    <div class="d-flex justify-content-center align-items-center container">
        <form action="{% url 'core:submit_otp' %}" method="post">
            {% csrf_token %}
        <div class="card py-5 px-3">
            <h5 class="m-0">Mobile phone verification</h5><span class="mobile-text">Enter the code we just send on your mobile phone <b class="text-danger">{{number}}</b></span>
            <div class="d-flex flex-row mt-5"><input type="text" class="form-control" autofocus="" name="otp"></div>
            <button class="btn btn-primary mt-3" type="submit">Submit</button>
            <a href="{% url 'core:phone_authentication' %}" style="text-decoration: none;"><div class="text-center mt-5"><span class="d-block mobile-text">Don't receive the code?</span><span class="font-weight-bold text-danger cursor">Resend</span></div></a>
        </div>
    </form>
    </div>
    {% endif %}
{% endblock %}

{% block script %}
<script>
    let camera_button = document.querySelector("#face_authentication-btn");
    let video = document.querySelector("#video");
    let canvas = document.querySelector("#canvas");

    camera_button.addEventListener('click', async function () {
        let stream = await navigator.mediaDevices.getUserMedia({
            video: true,
            audio: false
        });
        video.srcObject = stream;


        setTimeout(() => {
            canvas.getContext('2d').drawImage(video, 0, 0, canvas.width, canvas.height);
            let image_data_url = canvas.toDataURL('image/jpeg', 1.0);

            // data url of the image
            // console.log(image_data_url);

            stream.getTracks().forEach(function (track) {
                track.stop();
            });
            $('#canvasData')[0].value = image_data_url;


            var formdata = document.querySelector('.face-recognation-form').submit();
        }, 3000);

    });

    function getCsrfToken(name) {
    // Split cookie string and get all individual name=value pairs in an array
    var cookieArr = document.cookie.split(";");

    // Loop through the array elements
    for (var i = 0; i < cookieArr.length; i++) {
        var cookiePair = cookieArr[i].split("=");

        /* Removing whitespace at the beginning of the cookie name
        and compare it with the given string */
        if (name == cookiePair[0].trim()) {
            // Decode the cookie value and return
            return decodeURIComponent(cookiePair[1]);
        }
    }

    // Return null if not found
    return null;
}

</script>
{% endblock %}

backend/templates/index.html
{% extends 'base.html' %}

{% block content %}
<div class="container-fluid">
   <div class="form-div">
    <h1>ATM LOGIN</h1>
    {% if message %}
    {% if message == 'Payment Successfull!!' %}
    <div class="alert alert-success">
        {{message}}
    </div>
    {% else %}
    <div class="alert alert-danger">
        {{message}}
    </div>
    {% endif %}
    {% endif %}
    <form action="{% url 'core:login' %}" method="POST" class="d-flex flex-row flex-wrap justify-content-center mt-3">
        {% csrf_token %}
        <input type="text" class="form-control" placeholder="Enter your Account Number" name="account" required>
        <Button class="btn btn-primary w-25 mt-4" type="submit">Login</Button>
    </form>
   </div>
</div>
{% endblock %}

backend/templates/succesfull.html
{% extends 'base.html' %}

{% block content %}
<div class="container-fluid">
        <div class="card" style="width: 25%!important;">
            <h1 class="mb-3">Payment Successfull</h1>
            <div class="d-flex flew-row justify-content-between">
                <p>Amount withdraw:</p>
                <p>{{amount_requested}}</p>
            </div>
            <div class="d-flex flew-row justify-content-between">
                <p>Remaining balance:</p>
                <p>{{user.balance}}</p>
            </div>
        </div>
</div>
{% endblock %}


{% block script %}
<script>
document.cookie = "account_id=; expires=Thu, 01 Jan 1970 00:00:00 UTC; path=/;";
</script>
{% endblock %}